Feature/temp
TheBlueLab/bluecarbone pull request #3
Opened 2021-03-09 17:56 UTC by diggercam

templating + new categorie

2021-03-09 20:31 UTC, MartinHerr requested changes

2021-03-09 20:31 UTC, MartinHerr commented on app/base/forms.py
> +        id="consttype", validators=[DataRequired()])
@diggercam I bet these fields are not Decimal fields. Maybe rather dropdowns or something similar?

2021-03-09 20:31 UTC, MartinHerr commented on app/base/forms.py
> +    cars = DecimalField(
@diggercam I'd rather use an IntegerField for this one.

2021-03-09 20:31 UTC, MartinHerr commented on app/base/models.py
> +        return f"InvestmentsValues('{self.paper}', '{self.carton}')"
@diggercam update the `__repr__` method to return the correct table fields.
`return f"InvestmentValues('{self.surface}', '{self.activity}', <and so on>)"`

2021-03-10 10:39 UTC, diggercam commented on app/base/forms.py
> +        id="consttype", validators=[DataRequired()])
Yes, I guess dropdown is the best option, but need to work on it. We can keep it as it for now, I'm not planning to include Investments category for RSE Occitanie first POC, not needed for most of the companies.

2021-03-10 10:41 UTC, diggercam commented on app/base/forms.py
> +    cars = DecimalField(
Same here, should in the end be a dropdown with metal or béton

2021-03-10 10:42 UTC, diggercam commented on app/base/models.py
> +    consttype = Column(Integer, nullable=False)
Yes, should be modified when we will have a clear view of the best way to implement the dropdown

2021-03-10 11:05 UTC, diggercam commented on app/base/models.py
> +        return f"InvestmentsValues('{self.paper}', '{self.carton}')"
done

2021-03-10 11:08 UTC, diggercam commented on app/base/templates/includes/sidebar.html
> +
Line 54-59 ? Am I missing something ?

2021-03-10 13:54 UTC, MartinHerr commented on app/base/templates/includes/sidebar.html
> +
My bad

2021-03-10 13:56 UTC, MartinHerr commented on app/base/models.py
> +        return f"InvestmentsValues('{self.paper}', '{self.carton}')"
If it is done, then you need to push your modification to this branch.

2021-03-12 23:52 UTC, MartinHerr commented
@diggercam j'ai réparé tous les éléments qui étaient cassés (je crois). La prochaine fois, si tu pouvais tester tes modifs avant de les pousser, pour vérifier qu'elles ne génèrent pas de régression, ce serait cool.

2021-03-12 23:55 UTC, MartinHerr approved these changes

2021-03-12 23:56 UTC, merged